add check ceph environment & improve usage help information
Signed-off-by: Min Chen <minchen@ubuntukylin.com>

diff --git a/common_h b/common_h
--- a/common_h
+++ b/common_h
@@ -5,22 +5,22 @@
 my_dir=$(dirname "$0")
 
 # admin node init path
-rbd_image=/var/rbd_image
+rbd_image=/var/rbd_tool/rbd_image
 database=$rbd_image/database
 image_coll_v1=$rbd_image/image_coll_v1
 image_coll_v2=$rbd_image/image_coll_v2
 pg_coll=$rbd_image/pg_coll
 images=$rbd_image/images
 images_meta=$rbd_image/images_meta
-default_backup_dir=/var/default_backup_dir
+default_backup_dir=/var/rbd_tool/default_backup_dir
 
 # admin node: image snap & nosnap
 nosnap= #$rbd_image/<image_name>/nosnap
 snap= #rbd_image/<image_name>/<snap_name>
 
 # osd node init path
-job_path=/var/osd_job
-single_node=/var/single_node
+job_path=/var/rbd_tool/osd_job
+single_node=/var/rbd_tool/single_node
 
 # osd node vars
 osd_env= #single_node/$cluster$id/osd_env
@@ -48,6 +48,47 @@ ssh_option="-o ConnectTimeout=1"
 function gen_md5()
 {
   echo $1|md5sum|awk '{print $1}'
+}
+
+# on each osd node
+# check ceph enviroment: ssh, ceph-kvstore-tool, osd_data_path 
+function check_ceph_env()
+{
+  local func="check_ceph_env"
+  if [ $# -lt 2 ];then
+    echo "$func: parameters: <node> <data_path>" 
+    exit
+  fi
+  local node=$1
+  local data_path=$2
+  local res=
+  local cmd=
+
+  trap 'echo [$node]: ssh failed; exit' INT HUP
+  ssh -o ConnectTimeout=1 $node "echo -n" </dev/null
+  res=$?
+  if [ $res -ne 0 ];then
+    echo "[$node]: ssh failed"
+    exit
+  fi
+
+  cmd=ceph-kvstore-tool
+  trap 'echo [$node]: $cmd failed; exit' INT HUP
+  ssh -o ConnectTimeout=1 $node "$cmd &>/dev/null;" </dev/null 
+  res=$?
+  # ceph-kvstore-tool will return 1 with no parameters input
+  if [ $res -ne 1 ];then
+    echo "[$node]: $cmd not installed"
+    exit
+  fi
+
+  trap 'echo [$node]: stat $data_path failed; exit' INT HUP
+  ssh -o ConnectTimeout=1 $node "stat $data_path &>/dev/null;"  </dev/null
+  res=$?
+  if [ $res -ne 0 ];then
+    echo "[$node]: $data_path not exists"
+    exit
+  fi
 }
 
 # osd node context : osd_data_path
@@ -107,10 +148,11 @@ function init_env_admin()
     exit
   fi
 
-  # we just judge if osd_host is filled
-  if [ -s $osd_host ];then
+  # we just judge if osd_host is needed to be updated
+  if [ -s $osd_host ] && [ $osd_host -nt $osd_host_path ];then
     return  
   fi
+  echo "$func: create osd_host ..."
   # create file: osd_host and osd_host_mapping
   >$osd_host
   >$osd_host_mapping
@@ -124,25 +166,30 @@ function init_env_admin()
     fi
     local node=`echo $line|awk '{print $1}'`
     if [ "$node"x = ""x ];then
-      echo "$func: osd_host_path : line $lineno: osd_host not input"
+      echo "$func: osd_host_path : line $lineno: osd hostname not input"
+      rm -rf $osd_host $osd_host_mapping
       exit
     fi
     local data_path=`echo $line|awk '{print $2}'`
     if [ "$data_path"x = ""x ];then
-      echo "$func: osd_host_path : line $lineno: osd_data not input"
+      echo "$func: osd_host_path : line $lineno: osd data_path not input"
+      rm -rf $osd_host $osd_host_mapping
       exit
     fi
     lines=$(($lines + 1))
     # in case : there are servral hostnames on the same node
     # just need output of `hostname`
-    local hostname_replica=
-    hostname_replica=`ssh $ssh_option $node "hostname" 2>/dev/null </dev/null`
-    if [ "$hostname_replica"x = ""x ];then
-      echo "$func: get remote hostname replica failed"
+    local hostname_alias=
+    hostname_alias=`ssh $ssh_option $node "hostname" 2>/dev/null </dev/null`
+    if [ "$hostname_alias"x = ""x ];then
+      echo "$func: osd_host_path: line $lineno: $node: get remote hostname alias failed"
+      rm -rf $osd_host $osd_host_mapping
       exit
     fi
-    echo "$node $hostname_replica" >>$osd_host_mapping
+    echo "$node $hostname_alias" >>$osd_host_mapping
     echo $node >> $osd_host
+    # check ceph env on remote osd
+    check_ceph_env $node $data_path
   done < $osd_host_path
 
   if [ $lines = 0 ];then
@@ -185,10 +232,6 @@ function admin_parse_osd()
 # for osd node
 function get_omap_list()
 {
-  # clear lock if exist
-  #if [ -e $omap_path/LOCK ];then
-  #  mv $omap_path/LOCK $omap_path/LOCK~
-  #fi
   ceph-kvstore-tool $omap_path list > $omap_list
 }
 
