recover snapshot in-progress
Signed-off-by: min chen <runpanamera@gmail.com>

diff --git a/database_h b/database_h
--- a/database_h
+++ b/database_h
@@ -49,6 +49,7 @@ function gather_hobject_common()
   if [ "$1"x = ""x ];then
     echo "$func: image_prefix not input"  
     exit
+    #return 2 #not exist
   fi
 
   local image_prefix=$1
@@ -71,8 +72,12 @@ function gather_hobject_common()
   # $images/$image_prefix/$image_prefix"_head"
   local image_hobjects_stable=$image_hobjects_dir/$image_prefix"$fsuffix"
 
-  mkdir -p $images_raw_dir
-  mkdir -p $image_hobjects_dir
+  if [ ! -e $image_raw_dir ];then
+    mkdir -p $images_raw_dir
+  fi
+  if [ ! -e $image_hobjects_dir ];then
+    mkdir -p $image_hobjects_dir
+  fi
 
   pushd $database >/dev/null
   local pattern=".*__"$hex_snap_id"_.*"
@@ -80,7 +85,7 @@ function gather_hobject_common()
   grep -r -E $dump_image_prefix""$pattern * >$image_hobjects_raw
   if [ "`cat $image_hobjects_raw`"x = ""x ];then
     echo "$func: image snap [ $image_prefix"$psuffix" ] is empty"
-    exit
+    return 61 #no data available
   fi
   popd >/dev/null
 
@@ -132,6 +137,7 @@ function gather_hobject_common()
   sort -t ' ' -k 4.1,4 -u $sort_image > $image_hobjects_stable
   
   #rm -rf $offset_dir_temp
+  return 0
 }
 
 function gather_hobject_nosnap()
@@ -349,7 +355,10 @@ function lookup_image()
     db_snap_image_size=`cat $result|awk '/^snapshot:/{print $4}'`
   else
     #save snaplist
-    local image_snaplist=$images/$image_name_in/snaplist
+    local image_snaplist=$images/$image_name_in/@snaplist
+    if [ ! -e $images/$image_name_in ];then
+      mkdir -p $images/$image_name_in
+    fi
     cat $result|awk '/^snapshot:/{print $2" "$3" "$4}' >$image_snaplist
   fi
   found=1
@@ -373,37 +382,125 @@ function discover_image_nosnap()
   lookup_image $1 # assign $image_prefix
   #echo "$func: image_prefix=$db_image_prefix"
   gather_hobject_nosnap $db_image_prefix 
+  if [ $? -ne 0 ];then
+    exit
+  fi
   local image_hobjects_stable_nosnap=$images/$db_image_prefix/$db_image_prefix"_head"
   local image_hobjects_dir=$images/$image_name_in
-  mkdir -p $image_hobjects_dir
+  if [ ! -e $image_hobjects_dir ];then
+    mkdir -p $image_hobjects_dir
+  fi
   # mv image_prefix to image_name
   mv $image_hobjects_stable_nosnap $image_hobjects_dir/$image_name_in
   rm -rf $images/$db_image_prefix
 }
 
+function gen_object_snap_mapping()
+{
+  local func="gen_object_snap_mapping"
+  if [ $# -lt 2 ];then
+    echo "$func: parameters number error"
+    exit
+  fi
+  local snapid=$1
+  local snapset_dir=$2
+   
+ 
+}
+
+function get_object_clone()
+{
+  local func="get_object_clone"
+  if [ $# -lt 4 ];then
+    echo "$func: parameters number error"
+    exit
+  fi
+
+  local object_offset_string=$1
+  local snapid=$2
+  local snaplist_path=$3
+  local snapset_output_dir=$4
+
+  local snap_coll_arr=(`
+  cat $snaplist_path|awk '{ if ($1 >= "'"$snapid"'") print "'"$snapset_output_dir"'/@"$1}'`) 
+
+  local hex_snapid=`printf "%x" $snapid`
+  pushd $snapset_output_dir >/dev/null
+  # grep pattern need to fix
+  #grep -r -E "data.*__"$hex_snapid"_"  `echo ${snap_coll_arr[@]}`
+  echo $object_offset_string
+  awk '/'"$object_offset_string"'/{print}' `echo ${snap_coll_arr[@]}`
+  popd >/dev/null
+}
+
+function gen_snapset_hobject()
+{
+  local func="gen_image_snapset"
+  if [ $# -lt 3 ];then
+    echo "$func: parameter number error"
+  fi
+  local image_prefix=$1
+  local snaplist_path=$2
+  local snapset_output_dir=$3
+  OIFS=$IFS
+  IFS=$'\n'
+  local snaparr=(`cat $snaplist_path`) 
+  for line in ${snaparr[@]}
+  do
+    OOIFS=$IFS
+    IFS=$' '
+    local field=(`echo $line`)
+    local snapid=${field[0]}
+    local image_hobjects_stable_snap=$images/$image_prefix/$image_prefix"_"$snapid
+    local image_snap=$snapset_output_dir/@$snapid
+    gather_hobject_snap $image_prefix $snapid 
+    if [ $? -ne 0 ];then
+      touch $image_snap
+    else 
+      mv $image_hobjects_stable_snap $image_snap
+    fi
+    IFS=$OOIFS
+  done
+  IFS=$OIFS
+}
+
 function discover_image_snap()
 {
   local func="discover_image_snap"
+  echo "$func ..."
 
   local snap_name=$2
+  #mkdir -p $images/$image_prefix
   lookup_image $1 $2 # input image_name and snap_name to lookup metadata and snap_id
   if [ "$db_snap_id"x = ""x ];then
+    echo "$func: lookup image failed to gen snapid"
     exit
   fi
   local image_nosnap=$images/$image_name_in 
   #check if image nosnap recovered
   if [ ! -s $image_nosnap ];then
     echo "$func: please recover image nosnap before recover with snap"
+    rm -rf $images/$db_image_prefix
     exit
   fi
-  gather_hobject_snap $db_image_prefix $db_snap_id
-  local image_hobjects_stable_snap=$images/$db_image_prefix/$db_image_prefix"_"$db_snap_id
-  echo "image_hobjects_stable_snap: $image_hobjects_stable_snap"
-  local image_hobjects_dir=$images/$image_name_in
-  local image_snap=$image_hobjects_dir/snap_$db_snap_id
-  mkdir -p $image_hobjects_dir
-  mv $image_hobjects_stable_snap $image_snap
+  local image_hobject_dir=$images/$image_name_in
+  local image_snap=$image_hobject_dir/@snap_$db_snap_id
+  local image_snaplist=$image_hobject_dir/@snaplist
+  local image_snapset_dir=$image_hobject_dir/@snapset_dir
+  if [ ! -e $image_hobject_dir ];then
+    mkdir -p $image_hobject_dir
+  fi
+  # only gen snapset one time
+  if [ ! -e $image_snapset_dir ];then
+    mkdir -p $image_snapset_dir
+    gen_snapset_hobject $db_image_prefix $image_snaplist $image_snapset_dir  
+  fi
   rm -rf $images/$db_image_prefix
+
+  #get_object_clone 0 $db_snap_id $image_snaplist $image_snapset_dir
+  #get_object_clone 1 $db_snap_id $image_snaplist $image_snapset_dir
+  #get_object_clone 2 $db_snap_id $image_snaplist $image_snapset_dir
+  get_object_clone "0000000000000003" $db_snap_id $image_snaplist $image_snapset_dir
 }
 
 # after discover_image_nosnap
@@ -427,12 +524,17 @@ function copy_image_nosnap_single_thread()
     echo "$func: image not found, maybe forget to discover_image"
     exit
   fi
-  mkdir -p $backup_dir
+  if [ ! -e $backup_dir ];then
+    mkdir -p $backup_dir
+  fi
 
   local image_dir=$backup_dir/$image_name_in
   local image_file=$image_dir/$image_name_in
-  local CURRENT=$image_dir/CURRENT
-  local LOCK=$image_dir/LOCK
+  local CURRENT=$image_dir/@CURRENT
+  local LOCK=$image_dir/@LOCK
+  if [ ! -e $image_dir ];then
+    mkdir -p $image_dir
+  fi
   if [ -e $LOCK ];then
     echo "$func: $LOCK is locked by other process"
     exit
@@ -440,7 +542,6 @@ function copy_image_nosnap_single_thread()
     touch $LOCK
   fi
 
-  mkdir -p $image_dir
   >$image_file
   truncate -s $db_image_size $image_file 
   echo "head">$CURRENT
@@ -515,12 +616,16 @@ function collect_image_snap_objects()
   local head_hobjects=$4
   local backup_dir=$5
 
-  local head_dir=$backup_dir/$image_name/head
-  local snap_dir=$backup_dir/$image_name/$snap_id
-  local CURRENT=$backup_dir/$image_name/CURRENT
+  local head_dir=$backup_dir/$image_name/@head
+  local snap_dir=$backup_dir/$image_name/@$snap_id
+  local CURRENT=$backup_dir/$image_name/@CURRENT
  
-  mkdir -p $head_dir
-  mkdir -p $snap_dir
+  if [ ! -e $head_dir ];then
+    mkdir -p $head_dir
+  fi
+  if [ ! -e $snap_dir ];then
+    mkdir -p $snap_dir
+  fi
 
   # snap_hobjects and head_hobjects are sorted
   local snap_node=
@@ -593,10 +698,10 @@ function collect_image_snap_objects()
     head_filename=$head_dir/$head_offset
 
  #   echo "$snap_node $snap_filename    $head_node $head_filename"
-    ssh $ssh_option $snap_node "cat $snap_hobject" > $snap_filename 
-    if [ ! -e $head_filename ];then
-      ssh $ssh_option $head_node "cat $head_hobject" > $head_filename 
-    fi
+    #ssh $ssh_option $snap_node "cat $snap_hobject" > $snap_filename 
+    #if [ ! -e $head_filename ];then
+    #  ssh $ssh_option $head_node "cat $head_hobject" > $head_filename 
+    #fi
     IFS=$OOIFS
 
     percent=`echo "scale=3; 100*$icount/$entry_count"|bc`
@@ -628,7 +733,7 @@ function copy_image_snap_single_thread()
     backup_dir=$4
   fi
 
-  local LOCK=$backup_dir/$image_name/LOCK
+  local LOCK=$backup_dir/$image_name/@LOCK
   if [ -e $LOCK ];then
     echo "$func: $LOCK is locked by other process"
     exit
@@ -663,9 +768,9 @@ function recover_image()
   else
   #recover with snap
     discover_image_snap $img_name $snap_name # get image meta
-    local snap_hobjects=$images/$image_name_in/snap_$db_snap_id
-    local head_hobjects=$images/$image_name_in/$image_name_in
+    #local snap_hobjects=$images/$image_name_in/@snap_$db_snap_id
+    #local head_hobjects=$images/$image_name_in/$image_name_in
     
-    copy_image_snap_single_thread $image_name_in $db_snap_id $snap_hobjects $head_hobjects $backup_dir
+    #copy_image_snap_single_thread $image_name_in $db_snap_id $snap_hobjects $head_hobjects $backup_dir
   fi
 }
