rbd_recover_tool: fixbug, osds on the same node share the same output file
Signed-off-by: Min Chen <runpanamera@gmail.com>

diff --git a/database_h b/database_h
--- a/database_h
+++ b/database_h
@@ -85,16 +85,20 @@ function gather_hobject_nosnap()
   BEGIN {
     pg_coll="'$pg_coll'"
     tmp_image="'$tmp_image'"
+    osd_host_mapping="'$osd_host_mapping'"
   }{ 
       # $2 = /var/lib/ceph/osd/ceph-1/current/2.d3_head/rb.0.1293.6b8b4567.000000000002__head_FB425CD3__2
 
-      split($2, arr1, "current/");   # {/var/lib/ceph/osd/ceph-1/, 2.d3_head/rb.0.1293.6b8b4567.000000000002__head_FB425CD3__2}
+      split($2, arr1, "/current/");   # {/var/lib/ceph/osd/ceph-1/, 2.d3_head/rb.0.1293.6b8b4567.000000000002__head_FB425CD3__2}
       split(arr1[2], arr2, "/");     # {2.d3_head, rb.0.1293.6b8b4567.000000000002__head_FB425CD3__2} 
       split(arr2[1], arr3, "_head"); # {2.d3,} 
 
-      hobject=$2
+      hobject=$2;
+      data_path=arr1[1];
+#      print data_path
       gsub(/\\u/, "\\\\\\\\\\\\\\\\u", hobject); # dump backslash to delay escape (\ -> \\)
-      node = $1;
+      "awk \"\\$1 == \\\""$1"\\\" {print \\$2}\" "osd_host_mapping" | head -n 1" | getline node
+      #print "node="node
       pgid = arr3[1];
 
       len=length(arr2);
@@ -106,9 +110,11 @@ function gather_hobject_nosnap()
       offset=offarr2[1];                   # 000000000002
 
       system("echo -n \""node" "pgid" "hobject" "offset" \" >>"tmp_image);
+      #system("echo -n \""node" "pgid" "hobject" "offset" \"");
       
       # find pg_epoch from pg_coll database
-      system("awk  \"\\$1 == \\\""node"\\\" && \\$2 == \\\""pgid"\\\" {print \\$3}\" "pg_coll" >>"tmp_image);
+      system("awk  \"\\$1 == \\\""node"\\\" && \\$2 == \\\""pgid"\\\" && \\$4 == \\\""data_path"\\\" {print \\$3}\" "pg_coll" >>"tmp_image);
+      #system("awk  \"\\$1 == \\\""node"\\\" && \\$2 == \\\""pgid"\\\" && \\$4 == \\\""data_path"\\\" {print \\$3}\" "pg_coll);
   }'
 
   local sort_image=$offset_dir_temp/sortimage
@@ -120,10 +126,11 @@ function gather_hobject_nosnap()
 }
 
 # select the max pg_epoch item of the same $field
+# if no same $field, choose the first 
 # format : "node $field pg_epoch"
 function choose_epoch()
 {
-  cat $1|sort -t ' ' -k 3.1,4.1nr|head -n 1;
+  cat $1|sort -t ' ' -k 3.1,3nr -k 2.1,2n |head -n 1;
 }
 
 # lookup image info , after scatter_node_jobs & gather_node_infos
@@ -146,6 +153,7 @@ function lookup_image()
   local result=/tmp/tmp_result.$$$$
   local res1=/tmp/tmp_res1.$$$$
   local res2=/tmp/tmp_res2.$$$$
+  local data_path=
 
   # image format v1
   {
@@ -174,9 +182,10 @@ function lookup_image()
       image_format=1
       echo -e "image_name:\t$image_name_in"
       echo -e "image_format:\t$image_format"
+      data_path=`echo $image_header_hobject|awk -F "/current" '{print $1}'`
  
       >$result
-      cmds="bash $job_path/osd_job do_image_metadata_v1 `dump_backslash $image_header_hobject`" 
+      cmds="bash $job_path/osd_job do_image_metadata_v1 $data_path `dump_backslash $image_header_hobject`" 
       ssh $ssh_option $node $cmds | tee $result
     fi
   }
@@ -185,9 +194,11 @@ function lookup_image()
   {
     cat $image_coll_v2|grep -E "/rbd\\\\uid\."$img_name"__" >$res2
     if [ -s $res2 ];then
-      #echo -n "$func: rbd_id = "
-      #choose_epoch $res2 | tee $item
-      choose_epoch $res2 > $item
+      echo -n "$func: rbd_id = "
+      choose_epoch $res2 | tee $item
+      #choose_epoch $res2 > $item
+  
+      cat $item|awk '{print $1}'
 
       if [ -e $item ];then
         node=`cat $item|awk '{print $1}'`
@@ -207,8 +218,9 @@ function lookup_image()
       image_format=2
       
       local tid=/tmp/image_id.$$$$
+      data_path=`echo $image_id_hobject|awk -F "/current" '{print $1}'`
       >$tid
-      cmds="bash $job_path/osd_job do_image_id `dump_backslash $image_id_hobject`" 
+      cmds="bash $job_path/osd_job do_image_id $data_path `dump_backslash $image_id_hobject`" 
       ssh $ssh_option $node $cmds > $tid
 
       local image_id=`cat $tid`
@@ -218,25 +230,72 @@ function lookup_image()
       pushd $database >/dev/null
       local pattern="header."$image_id"__head"
       local tcoll=/tmp/tmp_image_head_coll.$$$$
-      local t_item=/tmp/tmp_item.$$$$
 
+      # hostname(by command hostname) in $pg_coll  maybe different from hostname in tcoll(input by user) 
+      # t_host:        hostname read from config file ($tcoll)
+      # t_host_remote: $(hostname) on osd node ($pg_coll)
       grep -r $pattern * >$tcoll
-      cat $tcoll |sed -n 's/\(.*\):\(.*\)\/\([0-9a-fA-F]\+\.[0-9a-fA-F]\+\)_head\/.*/\1 \3/p' \
-      | xargs -n 1 -I @ grep @ $pg_coll >$t_item;
+      popd >/dev/null
+
+      local t_host=(`cat $tcoll|awk -F ":" '{print $1}'`)
+      local t_pgid=(`cat $tcoll|awk -F ":" '{print $2}'|sed -n 's/.*\/\([0-9a-fA-F]\+\.[0-9a-fA-F]\+\)_head\/.*/\1/p'`)
+      local t_hobject=(`cat $tcoll|awk -F ":" '{print $2}'`)
+      local t_data_path=(`cat $tcoll|awk -F ":" '{split($2, arr, "/current/"); print arr[1];}'`)
+      rm -f $tcoll
+      declare -a t_host_remote
+
+      #if there is no failed pg migration, number of t_host is replica num
+      #usually 3, 4, 5 ...
+      local t_hostname=/tmp/t_hostname.$$$$
+      for ((i=0; i<${#t_host[*]}; i++))
+      do
+	ssh $ssh_option ${t_host[$i]} "hostname" >$t_hostname
+	if [ $? != 0 ];then
+	  echo "$func: ${t_host[$i]} get host_remote failed"
+	  exit
+	fi
+        t_host_remote[$i]=`cat $t_hostname`	
+      done
+      rm -f $t_hostname
+
+
+      local t_item=/tmp/tmp_item.$$$$
+      local tmp_item=/tmp/tmp_tmp_item.$$$$
       
-      node=`choose_epoch $t_item|awk '{print $1}'`
-      image_header_hobject=`cat $tcoll|awk -F ":" /$node/'{print $2}'`
+      >$tmp_item
+      for ((i=0; i<${#t_host_remote[*]}; i++ ))
+      do
+	local node=${t_host_remote[$i]}
+	local pgid=${t_pgid[$i]}
+	awk '$1 == "'"$node"'" && $2 == "'"$pgid"'" {print}' $pg_coll >>$tmp_item
+      done
+
+      # t_item: <remote_hostname> <pgid> <epoch> <data_path>
+      sort -u $tmp_item >$t_item
+      rm -f $tmp_item
+
+      local entry=`choose_epoch $t_item` #t_host_remote
+      rm -f $t_item
+
+      node=`echo $entry|awk '{print $1}'`
+      data_path=`echo $entry|awk '{print $4}'`
       if [ "$node"x = ""x ];then
         echo "$func: v2 node is NULL (to get image_header_hobject)"
         exit
       fi
+
+      for ((i=0; i<${#t_host_remote[*]}; i++))
+      do
+	if [ "${t_host_remote[$i]}"x = "$node"x ] && [ "${t_data_path[$i]}"x = "$data_path"x ];then
+	  image_header_hobject=${t_hobject[$i]}
+	  break
+	fi
+      done
+      
       if [ "$image_id_hobject"x = ""x ];then
         echo "$func: v2 image_header_hobject is NULL"
         exit
       fi
-      rm -f $t_item
-      rm -f $tcoll
-      popd >/dev/null
 
       check_osd_process $node
      
@@ -244,8 +303,9 @@ function lookup_image()
       echo -e "image_name:\t$image_name_in"
       echo -e "image_format:\t$image_format"
 
+      #data_path=`echo $image_header_hobject|awk -F "/current" '{print $1}'`
       >$result
-      cmds="bash $job_path/osd_job do_image_metadata_v2 $image_id `dump_backslash $image_header_hobject`" 
+      cmds="bash $job_path/osd_job do_image_metadata_v2 $data_path $image_id `dump_backslash $image_header_hobject`" 
       ssh $ssh_option $node $cmds | tee $result
     fi
   }
